### ISSUE TITLE
[0.7.9] Crashes with AttributeError: 'NoneType' object has no attribute 'itermatch'

### ISSUE THREAD

**Issue by hartwork** [pkgcore/pkgcheck#266]
```console
# pwd
[..]/dev-python/ipython
# pkgcheck scan "$(basename $(dirname $(pwd)))/$(basename $(pwd))"
updating gentoo profiles cache: x86            
updating eclass cache: xorg-3             
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkgcheck/pipeline.py", line 181, in _run_checks
    results.extend(pipe.run(restrict))
  File "/usr/lib/python3.7/site-packages/pkgcheck/pipeline.py", line 293, in run
    yield from check.feed(item)
  File "/usr/lib/python3.7/site-packages/pkgcheck/checks/stablereq.py", line 68, in feed
    match = next(self.modified_repo.itermatch(pkg.versioned_atom))
AttributeError: 'NoneType' object has no attribute 'itermatch'
```

**Comment by radhermit** [comment]
That was fixed in git with https://github.com/pkgcore/pkgcheck/commit/cdd2037e9d83414d1a2f75e78f211e0ccee0533b.

**Comment by radhermit** [comment]
Also, you could try forcibly regenerating the git cache with something like ``pkgcheck -uft git`` which should fix it.

**Comment by hartwork** [comment]
> That was fixed in git with [cdd2037](https://github.com/pkgcore/pkgcheck/commit/cdd2037e9d83414d1a2f75e78f211e0ccee0533b).

Okay cool.


> Also, you could try forcibly regenerating the git cache with something like `pkgcheck cache -uft git` which should fix it.

I tried, still crashes with the same backtrace:

```console
# pkgcheck cache -uft git
updating git cache: commit date: 2015-08-08

# pkgcheck scan "$(basename $(dirname $(pwd)))/$(basename $(pwd))"
[..]
AttributeError: 'NoneType' object has no attribute 'itermatch'
```

**Comment by hartwork** [comment]
@radhermit any chance for a new release? Should I cherry-pick the fix to -r1 in Gentoo myself? This bug is really standing in my way of maintaining packages.

**Comment by radhermit** [comment]
> @radhermit any chance of a new release?

Some chance, but there are a few outstanding issues to finish in the dep stack.

> Should I cherry-pick the fix to -r1 in Gentoo myself?

I wouldn't recommend that since there are other related commits that you'd have to pull as well since git support was refactored a decent amount, but technically I'm not a maintainer for the ebuilds in the tree anymore so I don't officially have much say over them.

> This bug is really standing in my way of maintaining packages.

One temporary workaround would be to disable the related check via config option until a release occurs.

**Comment by hartwork** [comment]
> Some chance, but there are a few outstanding issues to finish in the dep stack.

I see.


> > Should I cherry-pick the fix to -r1 in Gentoo myself?
> 
> I wouldn't recommend that since there are other related commits that you'd have to pull as well since git support was refactored a decent amount,

I see.

> but technically I'm not a maintainer for the ebuilds in the tree anymore so I don't officially have much say over them.

I see you dropped maintainership about a year ago. Okay.


> > This bug is really standing in my way of maintaining packages.
> 
> One temporary workaround would be to disable the related check via config option until a release occurs.

Good idea, I never configured anything about it so far. This worked: :tada: 
```console
# cat ~/.config/pkgcheck/pkgcheck.conf
[DEFAULT]
checks = -StableRequestCheck
```

Thank you! :pray:

**Comment by radhermit** [comment]
> @radhermit any chance of a new release?

Just fyi, this is available in 0.8.1 now but I'm not sure if that's in the tree yet since I'm not maintaining the ebuild anymore.

**Comment by hartwork** [comment]
@radhermit thanks for the ping about it. I would love to ùse it, and there is an ebuild in Gentoo by now but it has been hard-masked like this in `/usr/portage/profiles/package.mask` for everyone:
```
# The new pkgcheck version triggers lots of false positives due
# to Prefix profiles being broken.  Bug #720224.
>=dev-util/pkgcheck-0.8
>=sys-apps/pkgcore-0.11
```
Are you aware? I see you're being addressed in https://bugs.gentoo.org/720224#c5 but I don't see you in the ticket.

**Comment by radhermit** [comment]
> Are you aware? I see you're being addressed in https://bugs.gentoo.org/720224#c5 but I don't see you in the ticket.

I tried to warn prefix devs to make some movement over a month ago (https://bugs.gentoo.org/720224#c17). In my opinion they've had plenty of time to fix things (months) but unfortunately haven't addressed the issue yet.

**Comment by hartwork** [comment]
@radhermit I see! I looked for "rad" rather than "Tim", my bad, sorry.
