### ISSUE TITLE
`pkgcheck scan` raise a ConfigurationError exception

### ISSUE THREAD

**Issue by bekcpear** [pkgcore/pkgcheck#328]
Version:
`pkgcheck 0.10.2-3-g371630c`

OS:
`gentoo`

python version: 
`python3.9`

I tried `0.9.7-r2` `0.10.1` and this version, all of them raise these exceptions, I don't know how to solve it..

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 419, in collapse_named_section
    result = self.collapse_section(section_stack, name)
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 499, in collapse_section
    collapsed = CollapsedConfig(type_obj, self._render_config_stack(type_obj, config_stack),
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 521, in _render_config_stack
    raise errors.ConfigurationError(f'Type of {key!r} unknown')
pkgcore.config.errors.ConfigurationError: Type of 'basedir' unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 571, in get_default
    defaults = self.types.get(type_name, {}).items()
  File "/usr/lib/python3.9/site-packages/snakeoil/klass.py", line 176, in __get__
    obj = self.function(instance)
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 509, in types
    obj = self.collapse_named_section(name)
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 424, in collapse_named_section
    raise errors.ConfigurationError(
pkgcore.config.errors.ConfigurationError: Collapsing section named 'sync:gentoo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.9/site-packages/pkgcheck/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.9/site-packages/pkgcheck/cli.py", line 21, in main
    return super().main()
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 169, in main
    self.options, func = self.parse_args(args=self.args, namespace=self.options)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 124, in parse_args
    self.handle_exec_exception(e)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 100, in parse_args
    options = self.parser.parse_args(args=args, namespace=namespace)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 1177, in parse_args
    args, unknown_args = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 1164, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.9/argparse.py", line 2042, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.9/argparse.py", line 2019, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.9/argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 518, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 1161, in parse_known_args
    namespace, args = functor(parser, namespace, args)
  File "/usr/lib/python3.9/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 324, in _setup_scan
    namespace.target_repo = _determine_target_repo(namespace)
  File "/usr/lib/python3.9/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 221, in _determine_target_repo
    for repo in namespace.domain.ebuild_repos_raw:
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 564, in __getattribute__
    val(self, name)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/arghparse.py", line 355, in __call__
    self.invokable(namespace, attr)
  File "/usr/lib/python3.9/site-packages/pkgcore/util/commandline.py", line 210, in store_default
    obj = config.get_default(config_type)
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 575, in get_default
    raise errors.ConfigurationError(
pkgcore.config.errors.ConfigurationError: Collapsing defaults for 'domain'
```

**Comment by radhermit** [comment]
It would help to have more information about the config setup, e.g. can you attach the output from ``pconfig dump``?

**Comment by bekcpear** [comment]
Hi, this is the `pconfig dump` output:

<details>
<summary>pconfig dump</summary>

```
'basic' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.BasicFormatter;
}

'benzene-overlay' {
    # typename of this section: repo
    class pkgcore.ebuild.repository.tree;
    # type: refs:cache
    cache 'cache:benzene-overlay';
    # type: list
    default_mirrors 'https://mirrors.tuna.tsinghua.edu.cn/gentoo/distfiles';
    # type: ref:repo_config
    repo_config 'conf:benzene-overlay';
}

'cache:benzene-overlay' {
    # typename of this section: cache
    class pkgcore.cache.flat_hash.md5_cache;
    # type: str
    location '/var/db/repos/benzene-overlay';
    # type: bool
    readonly True;
}

'cache:gentoo' {
    # typename of this section: cache
    class pkgcore.cache.flat_hash.md5_cache;
    # type: str
    location '/var/db/repos/gentoo.git/gentoo';
    # type: bool
    readonly True;
}

'cache:gentoo-zh' {
    # typename of this section: cache
    class pkgcore.cache.flat_hash.md5_cache;
    # type: str
    location '/var/db/repos/gentoo-zh';
    # type: bool
    readonly True;
}

'cache:guru' {
    # typename of this section: cache
    class pkgcore.cache.flat_hash.md5_cache;
    # type: str
    location '/var/db/repos/guru';
    # type: bool
    readonly True;
}

'cache:local' {
    # typename of this section: cache
    class pkgcore.cache.flat_hash.md5_cache;
    # type: str
    location '/var/db/repos/local';
    # type: bool
    readonly True;
}

'cache:ryans' {
    # typename of this section: cache
    class pkgcore.cache.flat_hash.md5_cache;
    # type: str
    location '/var/db/repos/ryans';
    # type: bool
    readonly True;
}

'conf:benzene-overlay' {
    # typename of this section: repo_config
    class pkgcore.ebuild.repo_objs.RepoConfig;
    # type: str
    config_name 'benzene-overlay';
    # type: str
    location '/var/db/repos/benzene-overlay';
    # type: lazy_ref:syncer
    syncer 'sync:benzene-overlay';
}

'conf:gentoo' {
    # typename of this section: repo_config
    class pkgcore.ebuild.repo_objs.RepoConfig;
    default true;
    # type: str
    config_name 'gentoo';
    # type: str
    location '/var/db/repos/gentoo.git/gentoo';
    # type: lazy_ref:syncer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 419, in collapse_named_section
    result = self.collapse_section(section_stack, name)
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 499, in collapse_section
    collapsed = CollapsedConfig(type_obj, self._render_config_stack(type_obj, config_stack),
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 521, in _render_config_stack
    raise errors.ConfigurationError(f'Type of {key!r} unknown')
pkgcore.config.errors.ConfigurationError: Type of 'basedir' unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/pconfig", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.9/site-packages/pkgcore/scripts/__init__.py", line 32, in run
    sys.exit(tool())
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.9/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.9/site-packages/pkgcore/scripts/pconfig.py", line 206, in dump_main
    dump_section(section, out)
  File "/usr/lib/python3.9/site-packages/pkgcore/scripts/pconfig.py", line 34, in dump_section
    val = val.collapse()
  File "/usr/lib/python3.9/site-packages/pkgcore/config/basics.py", line 164, in collapse
    config = self.cached_config = self._collapse()
  File "/usr/lib/python3.9/site-packages/pkgcore/config/basics.py", line 184, in _collapse
    return self.central.collapse_named_section(self.name)
  File "/usr/lib/python3.9/site-packages/pkgcore/config/central.py", line 424, in collapse_named_section
    raise errors.ConfigurationError(
pkgcore.config.errors.ConfigurationError: Collapsing section named 'sync:gentoo'
```

</details>

And I found the reason. 

I override the default settings with the following in `/etc/portage/repos.conf/gentoo.conf`:

```
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo.git/gentoo
auto-sync = no
sync-type =
sync-uri =
sync-rsync-verify-jobs =
sync-rsync-verify-metamanifest =
sync-rsync-verify-max-age =
sync-openpgp-key-path =
sync-openpgp-keyserver =
sync-openpgp-key-refresh-retry-count =
sync-openpgp-key-refresh-retry-overall-timeout =
sync-openpgp-key-refresh-retry-delay-exp-base =
sync-openpgp-key-refresh-retry-delay-max =
sync-openpgp-key-refresh-retry-delay-mult =
sync-webrsync-verify-signature =
```

The error occurs due to the empty values, if I comment these empty settings, the error goes away.

**Comment by radhermit** [comment]
Fixed in https://github.com/pkgcore/pkgcore/commit/a4c98418228d97bb3d35b0f7b4e52f6cb2bde32c.

**Comment by xgqt** [comment]
Looks like this error is back

```
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 421, in collapse_named_section
    result = self.collapse_section(section_stack, name)
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 502, in collapse_section
    self._render_config_stack(type_obj, config_stack),
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 527, in _render_config_stack
    raise errors.ConfigurationError(f"Type of {key!r} unknown")
pkgcore.config.errors.ConfigurationError: Type of 'location' unknown

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 574, in get_default
    defaults = self.types.get(type_name, {}).items()
               ^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/klass/properties.py", line 100, in __get__
    obj = self.function(instance)
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 515, in types
    obj = self.collapse_named_section(name)
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 426, in collapse_named_section
    raise errors.ConfigurationError(
        f"Collapsing section named {name!r}"
    ) from e
pkgcore.config.errors.ConfigurationError: Collapsing section named 'conf:myov'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.14/pkgcheck", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.14/site-packages/pkgcheck/scripts/__init__.py", line 48, in main
    run(os.path.basename(sys.argv[0]))
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/pkgcheck/scripts/__init__.py", line 40, in run
    sys.exit(tool())
             ~~~~^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/tool.py", line 86, in __call__
    ret = self.main()
  File "/usr/lib/python3.14/site-packages/pkgcheck/cli.py", line 20, in main
    return super().main(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/tool.py", line 195, in main
    self.handle_exec_exception(e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/tool.py", line 177, in main
    self.options, func = self.parse_args(
                         ~~~~~~~~~~~~~~~^
        args=self.args, namespace=self.options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/tool.py", line 130, in parse_args
    self.handle_exec_exception(e)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/tool.py", line 107, in parse_args
    options = self.parser.parse_args(args=args, namespace=namespace)
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/arghparse.py", line 1339, in parse_args
    args, unknown_args = self.parse_known_args(args, namespace)
                         ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/arghparse.py", line 1322, in parse_known_args
    namespace, args = self._parse_known_args(
                      ~~~~~~~~~~~~~~~~~~~~~~^
        args, namespace, intermixed=False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.14/argparse.py", line 2274, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib/python3.14/argparse.py", line 2249, in consume_positionals
    take_action(action, args)
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/argparse.py", line 2118, in take_action
    action(self, namespace, argument_values, option_string)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/arghparse.py", line 605, in __call__
    namespace, arg_strings = parser.parse_known_args(arg_strings, namespace)
                             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/arghparse.py", line 1315, in parse_known_args
    namespace, args = functor(parser, namespace, args)
                      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 396, in _setup_scan
    namespace.target_repo = _determine_target_repo(namespace)
                            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 283, in _determine_target_repo
    for repo in namespace.domain.ebuild_repos_raw:
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/arghparse.py", line 657, in __getattribute__
    val(self, name)
    ~~~^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/snakeoil/cli/arghparse.py", line 441, in __call__
    self.invokable(namespace, attr)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.14/site-packages/pkgcore/util/commandline.py", line 228, in store_default
    obj = config.get_default(config_type)
  File "/usr/lib/python3.14/site-packages/pkgcore/config/central.py", line 578, in get_default
    raise errors.ConfigurationError(
        f"Collapsing defaults for {type_name!r}"
    ) from e
pkgcore.config.errors.ConfigurationError: Collapsing defaults for 'domain'
```

the conf in question:

```
[myov]
auto-sync = no
location = /home/xy/source/public/gitlab.com/xgqt/myov/
masters = gentoo
priority = 300
```

Command: `pkgcheck scan --jobs="8" --verbose --exit="error" --commits`

This is live build of pkgcheck: `pkgcheck 0.10.40-18-gf3865cc -- Thu Apr 23 17:20:24 2026`

```
f3865cc8dc10419532e71d8d8ca137288c4cc3dc                https://anongit.gentoo.org/git/proj/pkgcore/pkgcheck
9551885b4f91659d8db027759b17f41157ec816e                https://anongit.gentoo.org/git/proj/pkgcore/pkgcore
f46f0cadca8654f457b4cde50e434404c4a60a7e                branch 'main' of https://anongit.gentoo.org/git/proj/pkgcore/pkgdev
b7f1668511bb9943df9158e512f844ea22c80145                https://anongit.gentoo.org/git/proj/pkgcore/snakeoil
```
